"""Type stubs for the compiled extension. The public API is openbim_ifcx."""

from typing import Dict, List, Optional

class IfcxError(Exception):
    code: str

class NativeFile:
    @staticmethod
    def parse(data: bytes) -> NativeFile: ...
    def write(self, pretty: bool = ...) -> str: ...
    def header_json(self) -> str: ...
    @property
    def node_count(self) -> int: ...
    def validate_json(self) -> str: ...

def compose_json(layers: List[bytes], imports: Optional[Dict[str, bytes]] = ...) -> str: ...
def validate_json(layers: List[bytes], imports: Optional[Dict[str, bytes]] = ...) -> str: ...
def export_glb(
    layers: List[bytes],
    imports: Optional[Dict[str, bytes]] = ...,
    y_up: bool = ...,
    origin_on_root: bool = ...,
) -> bytes: ...
