import { readFileSync } from 'node:fs'

import { defineConfig } from 'vitepress'

import { diagramPlugin } from './diagram-plugin.ts'

// Both files are generated by `cargo run -p xtask -- docs` from the ADR files
// and the crate manifests; the gate fails when they are stale. Reading them
// here means a new ADR or crate reaches the sidebar with no edit to this file.
function data(name: string) {
  return JSON.parse(readFileSync(new URL('./data/' + name, import.meta.url), 'utf8'))
}

const adrs: { number: string; slug: string; title: string }[] = data('adrs.json')
const crates: { name: string; lib: string | null }[] = data('crates.json')

// The viewer (demo/, a Vite app) and rustdoc are built separately and
// copied into dist/viewer/ and dist/api/rustdoc/ by the Pages workflow, so
// links to them are plain links that leave the VitePress app.
const viewer = { text: 'Viewer', link: '/viewer/', target: '_self' }

const guide = [
  {
    text: 'Guide',
    items: [
      { text: 'Install', link: '/guide/install' },
      { text: 'Rust', link: '/guide/rust' },
      { text: 'JavaScript', link: '/guide/javascript' },
      { text: 'Python', link: '/guide/python' },
      { text: 'The viewer', link: '/guide/viewer' },
    ],
  },
]

const reference = [
  {
    text: 'Reference',
    items: [{ text: 'All crates', link: '/reference/' }].concat(
      crates.map(function (krate) {
        return { text: krate.name, link: '/reference/crates/' + krate.name }
      }),
    ),
  },
  { text: 'API', items: [{ text: 'Rust API (rustdoc)', link: '/api/' }] },
]

const project = [
  {
    text: 'Status',
    items: [
      { text: 'Capabilities', link: '/capabilities' },
      { text: 'Upstream parity and drift', link: '/evidence' },
    ],
  },
  {
    text: 'Decision records',
    items: [{ text: 'Index', link: '/adr/' }].concat(
      adrs.map(function (adr) {
        return { text: adr.number + ' · ' + adr.title, link: '/adr/' + adr.slug }
      }),
    ),
  },
  {
    text: 'Project',
    items: [
      { text: 'Changelog', link: '/project/changelog' },
      { text: 'Contributing', link: '/project/contributing' },
      { text: 'Releasing a crate', link: '/project/releasing' },
    ],
  },
]

export default defineConfig({
  title: 'openbim-ifcx',
  description: 'IFC5 / IFCX for Rust, JavaScript and Python: lossless read and write, layer composition, validation and GLB export.',
  lang: 'en-US',
  base: '/ifcx/',
  cleanUrls: true,
  lastUpdated: true,
  // AGENTS.md files are agent context beside the site sources, not pages.
  srcExclude: ['**/AGENTS.md'],
  // rustdoc and the viewer are copied into dist/ after this build runs, so
  // VitePress cannot see them here. Scoped to those prefixes: every other
  // dead link still fails the build.
  ignoreDeadLinks: [/^\/api\/rustdoc\//, /^\/viewer\//],
  markdown: {
    // Generated pages delimit their regions with HTML comments; with
    // `html: false` markdown-it would show them as text. All content is
    // this repository's own.
    html: true,
    config: diagramPlugin,
  },
  sitemap: { hostname: 'https://openbimrs.github.io/ifcx/' },
  head: [
    ['link', { rel: 'icon', href: '/ifcx/logo.svg', type: 'image/svg+xml' }],
    ['meta', { name: 'theme-color', content: '#0f766e' }],
  ],
  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'openbim-ifcx',
    nav: [
      { text: 'Guide', link: '/guide/install', activeMatch: '^/guide/' },
      { text: 'Reference', link: '/reference/', activeMatch: '^/(reference|api)/' },
      { text: 'Capabilities', link: '/capabilities', activeMatch: '^/(capabilities|evidence)' },
      { text: 'ADRs', link: '/adr/', activeMatch: '^/adr/' },
      { text: 'Changelog', link: '/project/changelog', activeMatch: '^/project/' },
      viewer,
    ],
    sidebar: {
      '/guide/': guide,
      '/reference/': reference,
      '/api/': reference,
      '/capabilities': project,
      '/evidence': project,
      '/adr/': project,
      '/project/': project,
    },
    socialLinks: [{ icon: 'github', link: 'https://github.com/openbimrs/ifcx' }],
    editLink: {
      pattern: 'https://github.com/openbimrs/ifcx/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },
    search: { provider: 'local' },
    outline: { level: [2, 3] },
    footer: {
      message:
        'Released under the MIT licence. No buildingSMART files or texts are published here.',
      copyright: 'Copyright (c) 2026 openbimrs contributors',
    },
  },
})
