//! `cargo run -p xtask -- docs`: regenerate, or check, every generated docs file.
//!
//! Each generator returns the content a file should have: either a whole
//! generated page, or a committed page with fresh content spliced between
//! its `<!-- NAME:BEGIN -->` / `<!-- NAME:END -->` markers. This module
//! compares and writes, so `--check` and regeneration can never disagree
//! about what "current" means.
//!
//! ## Internal split
//!
//! - `release.rs`: released versions and registries, from changelogs and manifests.
//! - `reference.rs`: one page per crate (manifest, README, public API,
//!   features, latest changes), the index, the sidebar data, the install
//!   table and the root README's crate table.
//! - `rust_api.rs`: a library crate's public API, read from its source.
//! - `bindings.rs`: the JavaScript and Python API tables of the binding pages.
//! - `changelog.rs`: `docs/project/changelog.md` from every `CHANGELOG.md`.
//! - `adr.rs`: the ADR index and the sidebar's ADR list.
//! - `contributing.rs`: the contributing and releasing pages, from `CONTRIBUTING.md`.
//! - `evidence.rs`: the upstream drift baseline on the evidence page.
//! - `capabilities.rs`: checks that the capability table names real crates.

mod adr;
mod bindings;
mod capabilities;
mod changelog;
mod contributing;
mod evidence;
mod reference;
mod release;
mod rust_api;

use std::path::{Path, PathBuf};

use crate::workspace::Workspace;

/// Directories whose every file is generated. A file there that no
/// generator produced is stale (a removed crate) and is deleted.
const MANAGED: &[&str] = &["docs/reference/crates"];

/// One generated file: where it lives and what it should contain.
pub(crate) struct Output {
    pub(crate) path: PathBuf,
    /// `None` when the file does not exist yet.
    pub(crate) current: Option<String>,
    pub(crate) updated: String,
}

impl Output {
    /// Read `rel` under the workspace root and derive its updated content.
    pub(crate) fn derive(
        workspace: &Workspace,
        rel: &str,
        update: impl FnOnce(&str) -> Result<String, String>,
    ) -> Result<Self, String> {
        let path = workspace.root.join(rel);
        let current = std::fs::read_to_string(&path)
            .map_err(|error| format!("cannot read {rel}: {error}"))?;
        let updated = update(&current).map_err(|error| format!("{rel}: {error}"))?;
        Ok(Self {
            path,
            current: Some(current),
            updated,
        })
    }

    /// A file whose whole content is generated.
    pub(crate) fn whole(workspace: &Workspace, rel: &str, updated: String) -> Self {
        let path = workspace.root.join(rel);
        let current = std::fs::read_to_string(&path).ok();
        Self {
            path,
            current,
            updated,
        }
    }

    fn stale(&self) -> bool {
        self.current.as_deref() != Some(self.updated.as_str())
    }
}

/// The banner every wholly generated Markdown page starts with, naming the
/// source to edit instead.
pub(crate) fn banner(source: &str) -> String {
    format!(
        "<!-- Generated by `cargo run -p xtask -- docs` from {source}. Do not edit: \
         change the source and regenerate. -->"
    )
}

/// Read a file under the workspace root.
pub(crate) fn read(workspace: &Workspace, rel: &str) -> Result<String, String> {
    std::fs::read_to_string(workspace.root.join(rel)).map_err(|error| format!("{rel}: {error}"))
}

pub(crate) fn run(check: bool) -> Result<(), String> {
    let workspace = Workspace::load()?;
    capabilities::check(&workspace)?;
    let mut outputs = vec![
        changelog::generate(&workspace)?,
        adr::index(&workspace)?,
        adr::sidebar(&workspace)?,
        evidence::generate(&workspace)?,
    ];
    outputs.extend(contributing::generate(&workspace)?);
    outputs.extend(reference::generate(&workspace)?);

    let relative = |path: &Path| {
        path.strip_prefix(&workspace.root)
            .unwrap_or(path)
            .display()
            .to_string()
    };
    let orphans = orphans(&workspace, &outputs);
    let stale: Vec<&Output> = outputs.iter().filter(|o| o.stale()).collect();
    if check {
        if stale.is_empty() && orphans.is_empty() {
            println!("docs in sync ({} generated files)", outputs.len());
            return Ok(());
        }
        let mut names: Vec<String> = stale.iter().map(|o| relative(&o.path)).collect();
        names.extend(
            orphans
                .iter()
                .map(|p| format!("{} (no longer generated)", relative(p))),
        );
        return Err(format!(
            "out of date: {}; run `cargo run -p xtask -- docs` and commit the result",
            names.join(", ")
        ));
    }
    for output in &stale {
        if let Some(parent) = output.path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|error| format!("cannot create {}: {error}", relative(parent)))?;
        }
        std::fs::write(&output.path, &output.updated)
            .map_err(|error| format!("cannot write {}: {error}", relative(&output.path)))?;
        println!("updated {}", relative(&output.path));
    }
    for orphan in &orphans {
        std::fs::remove_file(orphan)
            .map_err(|error| format!("cannot remove {}: {error}", relative(orphan)))?;
        println!("removed {}", relative(orphan));
    }
    if stale.is_empty() && orphans.is_empty() {
        println!("docs already in sync");
    }
    Ok(())
}

/// Files in a managed directory that no generator produced.
fn orphans(workspace: &Workspace, outputs: &[Output]) -> Vec<PathBuf> {
    let mut out = Vec::new();
    for dir in MANAGED {
        let Ok(entries) = std::fs::read_dir(workspace.root.join(dir)) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_file() && !outputs.iter().any(|o| o.path == path) {
                out.push(path);
            }
        }
    }
    out.sort();
    out
}
